apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: o4v6t09v1-nodejs
  janus-idp.io/tekton: o4v6t09v1-nodejs
  backstage.io/kubernetes-id: o4v6t09v1-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o4v6t09v1-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
